### PR TITLE
fix: invalidate styles cache on styles update

### LINKED ISSUE #784: Hot style preview in user stylesheet without reloading Atom
It doesn't work to change the color in atom stylesheet.

```css
.minimap .cursor-line {
  background: green;
}
```

related https://github.com/atom-minimap/minimap-cursorline/issues/35

### PR DESCRIPTION
**Pull request by UziTech**
fixes #784

### CODE REVIEW

File: lib/main.js [hunk 1]
```diff
@@ -407,16 +407,21 @@ function initSubscriptions() {
...
     treeSitterWarning()
   )
 }
 
+function updateStyles() {
+  domStylesReader.invalidateDOMStylesCache()
+  editorsMinimaps.forEach((minimap) => {
+    atom.views.getView(minimap).requestForcedUpdate()
+  })
+}
```
Comment (UziTech) [inline lib/main.js:423]: We might want to debounce this function since it looks like Atom calls it multiple times when styles.less is changed.

Comment (UziTech) [reply lib/main.js]: I see we have underscore-plus as a dependency so this should be easy.

File: lib/main.js [hunk 2]
```diff
@@ -7,6 +7,7 @@ import config from "./config.json"
 import * as PluginManagement from "./plugin-management"
 import { treeSitterWarning } from "./performance-monitor"
 import DOMStylesReader from "./dom-styles-reader"
+import { debounce } from "underscore-plus"
```
Comment (aminya) [inline lib/main.js:10]: Could you please add [the debounce function](https://github.com/jashkenas/underscore/blob/master/modules/debounce.js#L1) to
https://github.com/UziTech/minimap/blob/update-styles/lib/deps/underscore-plus.js

Or directly import it from `underscore`? `underscore-plus` is not tree-shakable

**Review by aminya — APPROVED** [review]
