### PR TITLE
fix: fix minimap on left width

### LINKED ISSUE #782: Editor tab ‘blends’ into minimap if it is on left and multiple panes are open
I prefer my minimap on the left but this is what happens to it:
image

It doesn't always happen, it just happens sometimes, specially when having multiple panes open.

When I move the minimap to the right side of the code editor window (which I don't like), the problem goes away.

1.54.0
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.7-3-MANJARO
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: Radeon RX 580 Series

### PR DESCRIPTION
**Pull request by UziTech**
fixes #782 

Removed hack for text editor margin and just changed flexbox order

### CODE REVIEW

**Comment by UziTech** [comment]
Turns out the reason for the hack was to fix a bug in Atom v1.18.0. I think it is safe to say that we should not support that version any more.

File: lib/minimap-element.js [hunk 1]
```diff
@@ -410,7 +377,7 @@ class MinimapElement {
     this.attachedToTextEditor = this.queryParentSelector("atom-text-editor") === this.minimap.getTextEditorElement()
 
     if (this.attachedToTextEditor) {
-      this.minimap.getTextEditorElement().setAttribute("with-minimap", "")
+      this.minimap.getTextEditorElement().setAttribute("with-minimap", this.displayMinimapOnLeft ? "left" : "right")
```
Comment (UziTech) [inline lib/minimap-element.js:380]: Turns out this actually wasn't needed for this fix but I wasn't sure if there was a reason not to have this. It might make other things easier to know if the minimap is on the left or right given the text editor.

**Comment by UziTech** [comment]
The only real issue here is whether left minimap with absolute mode should float over the gutter or should absolute mode not do anything different if minimap is on the left?

image

**Comment by aminya** [comment]
> The only real issue here is whether left minimap with absolute mode should float over the gutter or should absolute mode not do anything different if minimap is on the left?
> 
> image image

We should disable absolute when it goes on the left. The absolute mode only makes sense for the right minimap.

File: lib/minimap-element.js (hunk 1 above)
Comment (aminya) [reply lib/minimap-element.js:380]: Yeah, it does not hurt. We are already setting the attribute, so it might be better to include more information.

**Comment by UziTech** [comment]
That is what I figured. This should be good to go I haven't found any other issues.

**Review by aminya — APPROVED** [review]
Thanks!

**Comment by aminya** [comment]
The test error is a usual flaky test. Not a problem.
