### PR TITLE
fix: getDevicePixelRatio will return 0 on Linux resulting in no minimap

### LINKED ISSUE #795: Minimap is not shown in Atom 1.56 and above - Linux
Atom: 1.56.0
Minimap: 4.39.14
OS: Ubuntu 20.04.2 LTS x86_64 
Kernel: 5.4.0-73-generic 
DE: GNOME 3.36.7
WM: Mutter
WM Theme: Adwaita 
Theme: Yaru [GTK2/3]

I honestly don't remember when I first noticed this, but right now minimap is not working.
When I enable it (Packages -> Minimap -> Toggle), the Minimap space appear on the side, but it only shows the gear, from which I can select the options, but nothing inside is shown, it's completely empty.
Interestingly, when I disable it again (as above, Packages -> Minimap -> Toggle), the entire Atom window is moved downwards by some 20 or 30 pixels (unless the window is maximized).

I've tried with different text file type and relative syntax highlighting (LaTex, C, Python, plain text, ...).

I've already tried to uninstall and reinstall Minimap.

### PR DESCRIPTION
**Pull request by aminya**
Fixes #795

### CODE REVIEW

File: lib/minimap.js [hunk 1]
```diff
@@ -860,7 +860,14 @@ export default class Minimap {
    * @returns {number} The devicePixelRatio in the Minimap
    */
   getDevicePixelRatio() {
-    return this.getDevicePixelRatioRounding() ? Math.floor(devicePixelRatio) : devicePixelRatio
+    if (this.getDevicePixelRatioRounding()) {
+      if (devicePixelRatio >= 0.5) {
+        return Math.round(devicePixelRatio)
+      } else {
+        return Math.round(devicePixelRatio * 10) / 10
```
Comment (Narann) [inline lib/minimap.js:867]: This would fail if `devicePixelRatio` is `0.049` (quite theoretical value, I know). Why not simply return the whole `devicePixelRatio`?

What is the benefit of having a rounded floating value instead of the full one? Why `0.8` is better than `0.8958333134651184`?

Why not simply:

```js
    return (devicePixelRatio >= 0.5) ? Math.round(devicePixelRatio) : devicePixelRatio
```

**Comment by Narann** [comment]
Thanks for the fix, by the way. :)

File: lib/minimap.js (hunk 1 above)
Comment (aminya) [reply lib/minimap.js:867]: > This would fail if devicePixelRatio is 0.049 (quite theoretical value, I know). Why not simply return the whole devicePixelRatio?


That's impossible. That would be a screen that is like a needle😄 

> What is the benefit of having a rounded floating value instead of the full one? Why 0.8 is better than 0.8958333134651184?

This makes all the calculations much faster as the engine would not need to calculate all the pixels accurately.

Comment (aminya) [reply lib/minimap.js]: https://github.com/atom-minimap/minimap/pull/799/commits/3c506862292a43d8ae0ecf4169ae642411a22080

**Comment by aminya** [comment]
You're welcome

File: lib/minimap.js (hunk 1 above)
Comment (aminya) [reply lib/minimap.js]: https://en.wikipedia.org/wiki/Fixed-point_arithmetic
